echo "theHindu"
perl theHindhu.pl
echo "timesofindia"
perl timesofindia.pl
echo "ndtv"
perl ndtv.pl
echo "deccanchronicle"
perl deccanchronicle.pl
echo "WallStreetJournal"
perl WallStreetJournal.pl
cat output.txt
perl t2h.pl
google-chrome https://www.thehindu.com/news/
google-chrome https://timesofindia.indiatimes.com/
google-chrome https://www.gadgetsnow.com/latest-news
google-chrome https://www.ndtv.com/
google-chrome https://www.deccanchronicle.com/nation
google-chrome https://www.wsj.com/india
google-chrome output.html
